apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: java-quarkus-170996227
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: java-quarkus-170996227
    app.kubernetes.io/part-of: test-app-170996227
  name: java-quarkus-170996227
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: java-quarkus-app
      app.kubernetes.io/instance: java-quarkus-170996227
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-quarkus-app
        app.kubernetes.io/instance: java-quarkus-170996227
    spec:
      containers:
      - image: quay.io/hacdev/uj6rdav2-tenant/test-app-170996227/java-quarkus-170996227@sha256:e152f51424a8930678e88ab5cdcceb7dfc0cca9c305a8370ff37a59029a56334
        name: my-java-quarkus
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
status: {}
